Course.create [
							 {:title => 'Engineering Strategies & Practice I', :courseCode => 'APS111', :year => "1", :session => 'F', :area => 0, :description => 'This course introduces and provides a framework for the design process. Students are introduced to communication as an integral component of engineering practice. The course is a vehicle for understanding problem solving and developing communications skills. This first course in the two Engineering Strategies and Practice course sequence introduces students to the process of engineering design, to strategies for successful team work, and to design for human factors, society and the environment. Students write team and individual technical reports and give presentations within a discussion group.', :lectureHours => 3, :labHours => 1, :tutorialHours => 1, :discipline => 'ALL', :antiDescription => 'This course formalizes intuitions or how to do engineering design and communication. There is a lot of theory about specific design techniques, and effective engineering communication. The course tends to get pretty boring, but make sure you understand broadly what each technique is about. Both the midterm and the final exam, are multiple choice, with a few short/long answer questions.'},
							 
							 {:title => 'Ethics in Engineering', :courseCode => 'APS150', :year => "1", :session =>'F', :area => 0, :description => 'An introduction to professional ethics and the Academic Code of Conduct. Topics include: the theory of ethics, professional code of ethics, ethics in the profession, proper use of intellectual property in the professional and in academic settings, plagiarism, the Academic Code of Conduct, and application of ethics in practice.', :lectureHours => 0, :labHours => 0, :tutorialHours => 1, :discipline => 'ALL'},
							 
							 {:title => 'Mechanics', :courseCode => 'CIV100', :year => "1", :session =>'F', :area => 0, :description => 'The principles of statics are applied to composition and resolution of forces, moments and couples. The equilibrium states of structures are examined. Throughout, the free body diagram concept is emphasized. Vector algebra is used where it is most useful, and stress blocks are introduced. Shear force diagrams, bending moment diagrams and stress-strain relationships for materials are discussed. Stress and deformation in axially loaded members and flexural members (beams) are also covered.', :lectureHours => 3, :labHours => 0, :tutorialHours => 2, :discipline => 'ALL'},
							 
							 {:title => 'Calculus A', :courseCode => 'MAT196', :year => '1', :session =>'F', :area => 0, :description => 'Limits and continuity, differentiation, maximum and minimum problems, definite and indefinite integrals, application of integration to geometry, mechanics, and other engineering problems, introduction to first order differential equations.', :lectureHours => 3, :labHours => 0, :tutorialHours => 1, :discipline => 'ECE'},
							 
							 {:title => 'Linear Algebra', :courseCode => 'MAT188', :year => '1', :session =>'F', :area => 0, :description => 'Systems of linear equations; matrices; determinants; vectors, lines and planes in 3 dimensions; Rn; vector spaces; eigenvalues and eigenvectors; introduction to products; applications.', :lectureHours => 3, :labHours => 0, :tutorialHours => 1, :discipline => 'ALL'},
							 
							 {:title => 'Computer Fundamentals', :courseCode => 'APS105', :year => '1', :session =>'F', :area => 0, :description => 'An introduction to computer systems and problem solving using computers. Topics include: the representation of information, programming techniques, programming style, basic loop structures, functions, arrays, strings, pointer-based data structures and searching and sorting algorithms. The laboratories reinforce the lecture topics and develops essential programming skills.', :lectureHours => 3, :labHours => 2, :tutorialHours => 1, :discipline => 'ECE'},
							 
							 {:title => 'Seminar Course: Introduction to Electrical and Computer Engineering', :courseCode => 'ECE101', :year => '1', :session =>'F', :area => 0, :description => 'This is a seminar series that will introduce first year students to the wealth of subjects within the field of Electrical and Computer Engineering. Instructors will be drawn from the various research groups within the Department. This course will be offered on a credit/no-credit basis. Credit will not be given to students who attend fewer than 70% of the seminars. Students who receive no credit for the course must re-take it in their 2F session. Students who have not received credit for this course at the end of their 2F session will not be permitted to register in session 2S.', :lectureHours => 1, :labHours => 0, :tutorialHours => 0, :discipline => 'ECE'},
							 
							 {:title => 'Engineering Strategies & Practice II', :courseCode => 'APS112', :year => '1', :session =>'S', :area => 0, :description => 'This course introduces and provides a framework for the design process, problem solving and project management. Students are introduced to communication as an integral component of engineering practice. The course is a vehicle for practicing team skills and developing communications skills. Building on the first course, this second course in the two Engineering Strategies and Practice course sequence introduces students to project management and to the design process in greater depth. Students work in teams on a term length design project. Students will write a series of technical reports and give a team based design project presentation.', :lectureHours => 3, :labHours => 2, :tutorialHours => 0, :discipline => 'ALL'},
							 
							 {:title => 'Calculus B', :courseCode => 'MAT197', :year => '1', :session =>'S', :area => 0, :description => 'Techniques of integration, introduction to second order differential equations, sequences and series, vector-valued functions, functions of several variables, partial differentiation. Applications to mechanics and other engineering problems.', :lectureHours => 3, :labHours => 0, :tutorialHours => 1, :discipline => 'ECE'},
							 
							 {:title => 'Introduction to Materials and Chemistry', :courseCode => 'APS104', :year => '1', :session =>'S', :area => 0, :description => 'This is a seminar series that will introduce first year students to the wealth of subjects within the field of Electrical and Computer Engineering. Instructors will be drawn from the various research groups within the Department. This course will be offered on a credit/no-credit basis. Credit will not be given to students who attend fewer than 70% of the seminars. Students who receive no credit for the course must re-take it in their 2F session. Students who have not received credit for this course at the end of their 2F session will not be permitted to register in session 2S.', :lectureHours => 1, :labHours => 0, :tutorialHours => 0, :discipline => 'ECE'},
							 
							 {:title => 'Dynamics', :courseCode => 'MIE100', :year => '1', :session =>'S', :area => 0, :description => 'This is an introductory course in materials science and physical chemistry. Topics include: fundamentals of atomic, structure, the nature of bonding, crystal structure and defects, the laws of chemical thermodynamics (including a discussion of enthalpy and entropy), reaction equilibrium, and phase equilibria. These basic principles provide the foundation for an exploration of structure-property relationships in metals, ceramics, and polymers, with emphasis on mechanical properties.', :lectureHours => 3, :labHours => 0, :tutorialHours => 1, :discipline => 'ECE'},
							 
							 {:title => 'Electrical Fundamentals', :courseCode => 'ECE110', :year => '1', :session =>'S', :area => 0, :description => "A simplified overview of the physics of electricity and magnetism: Coulomb's law, Gauss' law, Ampere's law, Faraday's law. Physics of capacitors, resistors, and inductors. An introduction to circuit analysis: resistive circuits, nodal and mesh analysis, network theorems. Natural and forced response of RL and RC circuits. Sinusoidal steady-state analysis and power in AC circuits.", :lectureHours => 3, :labHours => 2, :tutorialHours => 1, :discipline => 'ECE'},
							 
							 {:title => 'Circuit Analysis', :courseCode => 'ECE212', :year => '2', :session =>'F', :area => 0, :description => 'Nodal and loop analysis and network theorems. Natural and forced response of RL, RC, and RLC circuits. Sinusoidal steady-state analysis. Frequency response; resonance phenomena; poles and zeros; applications of the Laplace transform.', :lectureHours => 3, :labHours => 3, :tutorialHours => 2, :discipline => 'ECE'},
							 
							 {:title => 'Digital Systems', :courseCode => 'ECE241', :year => '2', :session =>'F', :area => 0},
							 {:title => 'Programming Fundamentals ', :courseCode => 'ECE244', :year => '2', :session =>'F', :area => 0},
							 {:title => 'Advanced Engineering Mathematics', :courseCode => 'MAT290', :year => '2', :session =>'F', :area => 0},
							 {:title => 'Calculus III', :courseCode => 'MAT291', :year => '2', :session =>'F', :area => 0},
							 
							 {:title => 'Signals and System', :courseCode => 'ECE216', :year => '2', :session =>'S', :area => 0},
							 {:title => 'Electric and Magnetic Fields', :courseCode => 'ECE221', :year => '2', :session =>'S', :area => 0},
							 {:title => 'Introductory Electronics', :courseCode => 'ECE231', :year => '2', :session =>'S', :area => 0},
							 {:title => 'Computer Organization', :courseCode => 'ECE243', :year => '2', :session =>'S', :area => 0},
							 {:title => 'Communication and Design', :courseCode => 'ECE297', :year => '2', :session =>'S', :area => 0},
							 
{:courseCode=>"ECE335H1", :title=>"Introduction to Electronic Devices", :session=>"F", :area=>1, :description=>"Electrical behaviour of semiconductor structures and devices. Metal-semiconductor contacts; pn junctions, diodes, photodetectors, LED's; bipolar junction transistors, Ebers-Moll and hybrid-pi models; field effect transistors, MOSFET, JFET/MESFET structures and models; thyristors and semiconductor lasers. ", :prerequisites=>"MAT291H1 F and ECE221H1 S and ECE231H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE442H1", :title=>"Introduction to Micro- and Nano-Fabrication Technologies", :session=>"F", :area=>1, :description=>"An introduction to the fundamentals of micro- and nano-fabrication processes with emphasis on cleanroom practices. The physical principles of optical lithography, electron-beam lithography, alternative nanolithography techniques, and thin film deposition and metrology methods. The physical and chemical processes of wet and dry etching. Cleanroom concepts and safety protocols. Sequential micro-fabrication processes involved in the manufacture of microelectronic and photonic devices. Imaging and characterization of micro- and nano-structures. Examples of practical existing and emerging micro- and nano-devices. Limited enrollment.", :prerequisites=>"ECE335H1 or ECE350H1", :corequisites=>nil, :lectureHours=>3.0, :labHours=>4.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE527H1", :title=>"Photonic Devices", :session=>"F", :area=>1, :description=>"This course will introduce students to a range of photonic components useful in many applications ranging from bio-photonics and sensors to optical communications. The students will gain a solid understanding of the fundamental phenomena involved in photonic devices operation and hence their design. Topics covered in this course include: birefringent media such as liquid crystal displays; polarization states of light and its uses in device applications; interaction of light with matter and its influence in device performance; the uses of Gaussian beams and resonators in free space optical systems; basics of guiding light; periodic structures and optical thin films; waveguide couplers and splitters for manipulating light; nano-optics and plasmonic waveguides.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE535H1", :title=>"Advanced Electronic Devices", :session=>"F", :area=>1, :description=>"Heterojunctions, SiGe, InP and GaSb HBTs.  MOS device scaling and scaling limits, Dennard's constant field scaling rules, device characteristics and short channel effects.  Charge quantization, gate stack, strain and substrate engineering in nanoscale MOSFETs.  Nanoscale CMOS fabrication process flow, isolation methods, strategies to suppress short channel effects, stress memorization techniques.  Technology CAD for process and device simulations.  SPICE models for circuit simulation.  SOI (Silicon on Insulator) technology, III-V FETs and graphene transistors.  High Power Devices:  LDMOS, AIGaN/GaN HEMTs.", :prerequisites=>"ECE335H1 F or ECE350H1 F", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE318H1", :title=>"Fundamentals of Optics", :session=>"S", :area=>1, :description=>"Geometric Optics: Spherical surfaces, lenses and mirrors, optical imaging systems, matrix method, and aberrations. Polarization:  Polarizer and polarizations, anisotropic materials, dichroism, birefringence, index ellipsoid, waveplates, optical activity, Faraday effect. Interference: superposition of waves, longitudinal and transverse coherence, Young's double-slit experiment, Michelson and Fabry-Perot interferometer, thin-films. Diffraction and Fourier Optics: diffraction theory, single and double slits, diffraction gratings, spatial filtering, basic optical signal processing.  (Background preparation in ECE320H1 F - Fields and Waves, or ECE357H1 S - Electromagnetic Fields, is strongly recommended.)", :prerequisites=>"ECE221H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE330H1", :title=>"Semiconductor and Device Physics", :session=>"S", :area=>1, :description=>"Wave and quantum mechanics, the Schrodinger equation, quantum wells and density of states. Quantum statistics, solid-state bonding and crystal structure. Electron waves, dispersion relation inside periodic media, Fermi level and energy bands. Physical understanding of semiconductors at equilibrium, intrinsic and extrinsic semiconductors and excess carriers.", :prerequisites=>"ECE221H1 S and ECE231H1 S. (Backround preparation in ECE320H1 F - Fields and Waves is strongly recommended).", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE469H1", :title=>"Optical Communications and Networks", :session=>"S", :area=>145, :description=>"This course provides an introduction to optical communication systems and networks at the system and functional level.  Applications range from telecommunication networks (short to long haul) to computing networks (chip-to-chip, on chip communications, optical backplanes).  Basic principles of optical transmission and associated components used for transmission of light and optical networks; system design tools for optical links; multi-service system requirements; optical network design tools (routing and wavelength assignment), network management and survivability.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics $ Control, communications & signal processing $ Computer hardware & computer networks", :exclusion=>"ECE425S or ECE467S", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE525H1", :title=>"Lasers and Detectors", :session=>"S", :area=>1, :description=>"This course focuses on photonic components which generate or absorb light. Lasers: spontaneous and stimulated emission, gain and absorption, gain broadening; modulation dynamics, mode-locking, Q-switching; semiconductor lasers. Photodetectors: absorption, photo-generated currents, noise in detection.", :prerequisites=>"One of ECE330/350H1 or PHY335/355H1, and one of ECE318/320/357H1 ECE318H1 S can also be taken as a co-requisite instead of a pre-requisite.)", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"PHY335H1", :title=>"Introduction to Quantum Mechanics", :session=>"S", :area=>17, :description=>"Review of elementary quantum mechanics, (photo-electric and Compton effects, Bohr model, de Broglie waves); some bound (harmonic oscillator, hydrogen atom) and unbound (potential barriers) solutions of the Schrodiner equation; probability interpretation; operators and the theory of measurement; expectation values and uncertainties; angular momentum (orbital and spin); magnetic resonance as an application.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Photonics & semiconductor physics $ Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE314H1", :title=>"Fundamentals of Electrical Energy Systems", :session=>"F", :area=>2, :description=>"Introduction to 3-phase systems, single line diagrams and complex power flow. Energy conversion via switch-mode power electronic circuits: DC/DC converters, DC/AC converters. Energy conversions via magnetic devices: Faraday's law for time varying fields, characterization of hysteresis and eddy current losses in magnetic materials, modelling of magnetic circuits, transformer and inductor modelling and design. Introduction to electromechanical energy conversion: Lorentz Force, concepts of energy, co-energy, forces between ferromagnetic materials carrying flux, simple magnetic actuators.", :prerequisites=>"ECE212H1 F and ECE221H1S and ECE231H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>"ECE315H1 F", :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE320H1", :title=>"Fields and Waves", :session=>"F", :area=>2, :description=>"Voltage and current waves on a general transmission line, reflections from the load and source, transients on the line, and Smith's chart. Maxwell's equations, electric and magnetic fields wave equations, boundary conditions, plane wave propagation, reflection and transmission at boundaries, constitutive relations, dispersion, polarization; Poynting vector; waveguides. ", :prerequisites=>"ECE221H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE510H1", :title=>"Introduction to Lighting Systems", :session=>"F", :area=>2, :description=>"An introduction to the physics of lighting systems (e.g. plasma physics, radiation spectrum, physics of light-emitting diodes) and the corresponding power electronic driver circuits (ballasts). The operating principles and the science behind different types of lamps are covered. These include incandescent, fluorescent, low and high pressure sodium, mercury, metal halide lamps and LED lighting systems. The designs and technical challenges of the electronic ballasts for each type of lighting source are discussed. Issues related to lighting regulations, layout, delivery, efficiency, control and the economic and environmental assessment of current lighting systems are briefly addressed.", :prerequisites=>"ECE314H1 F or ECE315H1 F or ECE 349H1 F or ECE359H1 F", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE524H1", :title=>"Microwave Circuits", :session=>"F", :area=>2, :description=>"The wave equation; losses in conductors and dielectrics; RF and microwave transmission lines; transients on transmission lines; matching networks; planar transmission lines (microstrip, stripline, coplanar waveguide); design with scattering parameters; 3- and 4-port RF devices (power dividers/combiners, couplers, isolators & circulators); coupled lines and devices; microwave active circuits (RF amplifiers, mixers, and receiver front ends); RF and microwave filters. The hands-on laboratories engage students in the design, simulation, fabrication, and test of practical passive and active microwave circuits using industry-standard RF/microwave simulation tools and measurement systems.", :prerequisites=>"ECE320H1 F or ECE357H1 S", :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE533H1", :title=>"Advanced Power Electronics", :session=>"F", :area=>2, :description=>"This course covers system issues associated with the design of switched mode power supplies for telecommunication, computer network and information applications. Topics to be covered include: power processing architectures; steady state analysis and component ratings; control loop modelling and control loop design; EMC regulatory issues.", :prerequisites=>"ECE314H1 F or ECE315H1 F or ECE349H1 F or ECE359H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"BME595H1", :title=>"Medical Imaging", :session=>"S", :area=>24, :description=>"This is a first course in medical imaging. It is designed as a final year course for engineers. It has a physical and mathematical approach emphasizing engineering concepts and design. It describes magnetic resonance and ultrasound and X ray imaging in detail. These topics allow engineers to apply principles learned in the first two years in: computer fundamentals, dynamics, calculus, basic EM theory, algebra and differential equations, signals systems. It is a depth course complementing the kernels: communication systems (modulation), fields and waves (wave propagation) and on probability and random processes (Poisson and Gaussian noise). It will introduce students to the concept of measurement as an \"inverse problem\". The laboratory will involve hands on NMR and Ultrasound measurements as well as image analysis of MRI data.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems $ Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE413H1", :title=>"Energy Systems and Distributed Generation", :session=>"S", :area=>2, :description=>"Three-phase systems; steady-state transmission line model; symmetrical three-phase faults; power system stability; symmetrical components; unsymmetrical faults and fault current calculation; distribution network; equivalent steady-state model of voltage-sourced converter; distributed energy resources (DR); distributed energy storage; interface between DR and power system.", :prerequisites=>"ECE314H1 F or ECE315H1 F or ECE349H1F or ECE359H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE422H1", :title=>"Radio and Microwave Wireless Systems", :session=>"S", :area=>2, :description=>"Analysis and design of systems employing radio waves, covering both the underlying electromagnetics and the overall system performance aspects such as signal-to-noise ratios. Transmission/reception phenomena include: electromagnetic wave radiation and polarization; elementary and linear dipoles; directivity, gain, efficiency; integrated, phased-array and aperture antennas; beam-steering; Friis transmission formulas. Propagation phenomena include: diffraction and wave propagation over obstacles; multipath propagation in urban environments; atmospheric and ionospheric effects. Receiver design aspects include: receiver figures of merit, noise in cascaded systems, noise figure, and noise temperature. System examples are: fixed wireless access; mobile and personal communication systems; wireless cellular concepts; satellite communications; radar; radiometric receivers; GPS.", :prerequisites=>"ECE320H1 F or ECE357H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE463H1", :title=>"Electric Drives", :session=>"S", :area=>2, :description=>"Electro-mechanical mechanisms for force and torque production in rotating machines. DC machine theory and DC machine dynamics, synchronous machines and their dynamics, stepper motors. Introduction to space vectors and vector control of AC machines.  Steady state and variable speed operation of the induction machine via V/f control.", :prerequisites=>"ECE314H1 F or ECE315H1 F or ECE349H1 F or ECE359H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Electromagnetics & energy systems", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE331H1", :title=>"Analog Electronics", :session=>"B", :area=>3, :description=>"Transistor amplifiers, including: differential and multistage amplifiers, integrated circuit biasing techniques, output stage design and IC amplifier building blocks. Frequency response of amplifiers at low, medium and high frequencies. Feedback amplifier analysis. Stability and compensation techniques for amplifiers using negative feedback.", :prerequisites=>"ECE212H1 F and ECE231H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE334H1", :title=>"Digital Electronics", :session=>"B", :area=>3, :description=>"Digital design techniques for integrated circuits. The emphasis will be on the design of logic gates at the transistor level. A number of different logic families will be described, but CMOS will be emphasized. Review of: device modeling, IC processing, and Spice simulation, simplified layout rules, inverter noise margins, transient response, and power dissipation, traditional CMOS logic design, transmission gates, RC timing approximations, input-output circuits, latches and flipflops, counters and adders, decoders and muxes, dynamic gates, SRAMs, DRAMs, and EEPROMs.", :prerequisites=>"ECE241H1 F and ECE231H1 S or ECE253H1 F and ECE360H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE446H1", :title=>"Sensory Communication", :session=>"F", :area=>34, :description=>"Physical acoustics, acoustic measurements, electroacoustic transducers, and physiological acoustics. Speech processing, speech recognition algorithms and signal processing by the auditory system. Engineering aspects of acoustic design. Electrical models of acoustic systems. Noise, noise-induced hearing loss, and noise control. Introduction to vision and other modalities. Musical and psychoacoustics.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics $ Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE512H1", :title=>"Analog Signal Processing Circuits", :session=>"F", :area=>3, :description=>"An overview of analog signal processing in both continuous-time and discrete-time. The design of analog filters including transfer function approximation using Matlab and implementation using active-RC, transconductance-C, and switched-capacitor circuits. Other topics include oversampling and noise in analog circuits.", :prerequisites=>"ECE331H1 F or ECE354H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE534H1", :title=>"Integrated Circuit Engineering", :session=>"F", :area=>3, :description=>"The course deals with the technology and design of analog, digital and RF integrated circuits, including exposure to computer aided IC design tools at the semiconductor process, device, and circuit layout level. Topics include: IC fabrication review, MOS IC process modules and components; RF (Bi) CMOS IC process modules and components; compact modelling, characterization and design automation; Bipolar/CMOS digital, analog, and RF IC building blocks; packaging and yield. The labs will expose students to the major design steps in the development of a multi-purpose (Bi) CMOS process.", :prerequisites=>"ECE331H1 F or ECE334H1 F/S and ECE335H1 F", :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE451H1", :title=>"VLSI Systems and Design", :session=>"S", :area=>35, :description=>"An introduction to the design, verification and layout of VLSI circuits for complex digital systems. The focus is on CMOS technology, using custom and standard cell-based design flows, and covering both design and computer-aided design techniques. Topics covered include deep sub-micron design, clocking techniques, physical design, sub-system design, power, testing, simulation, placement/routing, synthesis, and test generation. The course has a major project component in which students design and produce a layout for a small microprocessor chip.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics $ Computer hardware & computer networks", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE530H1", :title=>"Analog Integrated Circuits", :session=>"S", :area=>3, :description=>"Review of MOSFET semiconductor device equations. Review of basic amplifier circuits. Basic CMOS op amp. Op amp compensation. Advanced op amp circuits: telescopic and folded-cascode op amps; fully-differential op amps. Comparators. Sample-and-hold circuits. Bandgap reference circuits. Nyquist-rate data converters: D/A converters, A/D converters.", :prerequisites=>"ECE331H1 F or ECE354H1 S", :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE532H1", :title=>"Digital Systems Design", :session=>"S", :area=>35, :description=>"Advanced digital systems design concepts including project planning, design flows, embedded processors, hardware/software interfacing and interactions, software drivers, embedded operating systems, memory interfaces, system-level timing analysis, clocking and clock domains. A significant design project is undertaken and implemented on an FPGA development board.", :prerequisites=>"ECE342H1 S or ECE352H1 F", :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Analog & digital electronics $ Computer hardware & computer networks", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE316H1", :title=>"Communication Systems", :session=>"B", :area=>4, :description=>"An introductory course in analog and digital communication systems. Analog and digital signals. Signal representation and Fourier transforms; energy and power spectral densities; bandwidth. Distortionless analog communication; amplitude, frequency and phase modulation systems; frequency division multiplexing. Sampling, quantization and pulse code modulation (PCM). Baseband digital communication; intersymbol interference (ISI); Nyquist's ISI criterion; eye diagrams. Passband digital communications; amplitude-, phase- and frequency-shift keying; signal constellations. Performance analysis of analog modulation schemes in the presence of noise. Performance analysis of PCM in noise.", :prerequisites=>"MAT290H1 F and ECE216H1 S or ECE355H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE302H1", :title=>"Probability and Applications", :session=>"B", :area=>477, :description=>"Events, sample space, axioms of probability. Discrete and continuous random variables, distribution and density functions. Bernoulli trials, Binomial, geometric, Poisson, exponential and Gaussian distributions. Expectation, moments, characteristic function, correlation coefficient. Functions of random variables. Random vectors, joint distributions, transformations. Applications will be chosen from communication theory, estimation and hypothesis testing, and other areas of electrical engineering.", :prerequisites=>"MAT290H1 F and MAT291H1 F and ECE216H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing $ Science/math electives $ Science/math electives", :exclusion=>"STA286H1 S", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE410H1", :title=>"Control Systems", :session=>"F", :area=>4, :description=>"State space analysis of linear systems, the matrix exponential, linearization of nonlinear systems. Structural properties of linear systems: stability, controllability, observability, stabilizability, and detectability. Pole assignment using state feedback, state estimation using observers, full-order and reduced-order observer design, design of feedback compensators using the separation principle, control design for tracking. Control design based on optimization, linear quadratic optimal control, the algebraic Riccati equation. Laboratory experiments include computer-aided design using MATLAB and the control of an inverted pendulum on a cart.", :prerequisites=>"ECE311H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>"ECE557H1 F", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE431H1", :title=>"Digital Signal Processing", :session=>"B", :area=>4, :description=>"An introductory course in digital filtering and applications. Introduction to real-world signal processing. Review of sampling and quantization of signals. Introduction to the discrete Fourier transform and its properties. The fast Fourier transform. Fourier analysis of signals using the discrete Fourier transform. Structures for discrete-time systems. Design and realization of digital filters: finite and infinite impulse response filters. DSP applications to communications: decimators and interpolators, estimation, equalization. DSP applications to multimedia: DCT and video coding.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE445H1", :title=>"Neural Bioelectricity", :session=>"F", :area=>4, :description=>"This course deals with generation, transmission and significance of bioelectricity in neural networks. Topics covered include: (i) Basic features of neural systems. (ii) Ionic transport mechanisms in neural membranes. (iii) Nonlinear circuit models of neuronal membranes. (iv) Propagation of electricity in neural cables. (v) Extracellular electric fields of cellular moving current sources. (vi) Biological neural networks. (vii) Artificial neural networks. (viii) Learning and memory in artificial neural networks. Laboratory topics include: (a) Measurement of surface potentials on human torsos. (b) Generation of cellular electricity in computer models of nonlinear circuits. (c) Propagation of bioelectricity in computer models of nonlinear neural cables. (d) Investigation of a computer model of a periform cortex network.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE537H1", :title=>"Random Processes", :session=>"F", :area=>4, :description=>"Introduction to the principles and properties of random processes, with applications to communications, control systems, and computer science. Random vectors, random convergence, random processes, specifying random processes, Poisson and Gaussian processes, stationarity, mean square derivatives and integrals, ergodicity, power spectrum, linear systems with stochastic input, mean square estimation, Markov chains, recurrence, absorption, limiting and steady-state distributions, time reversibility, and balance equations.", :prerequisites=>"STA286H1 S and ECE355H1 F or ECE302H1 F/S", :corequisites=>"ECE355H1 F (can be taken at the same time as ECE537H1 F)", :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE311H1", :title=>"Dynamic Systems and Control", :session=>"S", :area=>4, :description=>"An introduction to dynamic systems and their control. Differential equation models of mechanical, electrical, and electromechanical systems. State variable form. Linearization of nonlinear models and transfer functions. Use of Laplace transform to solve ordinary differential equations. Conversion of models from state variable form to transfer function representation and vice versa. Block diagrams and their manipulation. Time response: transient analysis and performance measures. Properties of feedback control systems. Steady state tracking: the notion of system type. The concept of stability of feedback systems, Routh-Hurwitz stability criterion. Frequency response and stability in the frequency domain. Root locus. Bode and Nyquist plots and their use in feedback control design.", :prerequisites=>"MAT290H1 F and MAT291H1 F and ECE216H1S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE411H1", :title=>"Real-Time Computer Control", :session=>"S", :area=>4, :description=>"Digital Control analysis and design by state-space methods. Introduction to scheduling of control tasks using fixed-priority protocols. Labs include control design using MATLAB and Simulink, and computer control of the inverted pendulum using a PC with real-time software.", :prerequisites=>"ECE311H1 S or ECE356H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE417H1", :title=>"Digital Communication", :session=>"S", :area=>4, :description=>"Basic concepts of digital communication. Baseband data transmission, intersymbol interference, Nyquist pulse shaping, equalization, line coding, multi-path fading, diversity. Binary and M-ary modulation schemes, synchronization. Signal space concepts, optimum receivers, coherent and noncoherent detectors. Information theory, source encoding, error control coding, block and convolutional codes.", :prerequisites=>"ECE302H1 F/S and ECE316H1 F/S, or STA286H1", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE462H1", :title=>"Multimedia Systems", :session=>"S", :area=>4, :description=>"Topics in the engineering area of multimedia systems with particular emphasis on the theory, design features, performance, complexity analysis, optimization and application of multimedia engineering technologies. Topics include sound/audio, image and video characterization, compression, source entropy and hybrid coding, transform coding, wavelet-based coding, motion estimation, JPEG coding, digital video coding, MPEG-1/2 coding, content-based processing, and MPEG-7.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>2.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE464H1", :title=>"Wireless Communication", :session=>"S", :area=>4, :description=>"The radio medium, radio communication system examples. Link budget: cable losses, propagation loss, antenna gains. Basic concepts of propagation: path loss, multi-path propagation and fading. Raleigh and Rician fading models, Doppler shift, delay spread, coherence time and coherence bandwidth of the channel. Analog modulation schemes and their bandwidths. Digital modulation schemes and their bandwidths and bit rates: BPSK, QPSK, MSK, GMSK. Basic concepts of speech coding. Error correction coding, interleaving, and multiple access frame structure. The physical layer description of the AMPS, IS-54, and GSM cellular systems. The cellular concept: frequency re-use, re-use cluster concept. Channel allocation. Cellular system architecture for AMPS, IS-54, and GSM. Hand-offs and transmitter power control. Cellular traffic, call blocking, concept of Erlangs. Basic ideas in spread spectrum modulation, spreading codes, bit error probability. Orthogonal and non-orthogonal CDMA Basic concepts in CDMA networks.", :prerequisites=>"ECE302H1 F/S and ECE316H1 F/S, or STA286H1", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE470H1", :title=>"Robot Modeling and Control", :session=>"S", :area=>4, :description=>"Classification of robot manipulators, kinematic modeling, forward and inverse kinematics, velocity kinematics, path planning, point-to-point trajectory planning, dynamic modeling, Euler-Langrange equations, inverse dynamics, joint control, computed torque control, passivity-based control, feedback linearization.", :prerequisites=>"ECE311H1 S or ECE356H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE516H1", :title=>"Intelligent Image Processing", :session=>"S", :area=>4, :description=>"This course provides the student with the fundamental knowledge needed in the rapidly growing field of Personal Cybernetics, including \"Wearable Computing\", \"Personal Technologies\", \"Human Computer Interaction (HCI),\" \"Mobile Multimedia,\" \"Augmented Reality,\" \"Mediated Reality,\" CyborgLogging,\" and the merging of communications devices such as portable telephones with computational and imaging devices.  The focus is on fundamental aspects and new inventions for human-computer interaction.  Topics to be covered include: mediated reality, Personal Safety Devices, lifelong personal video capture, the Eye Tap principle, collinearity criterion, comparametric equations, photoquantigraphic imaging, lightvector spaces, anti-homomorphic imaging, application of personal imaging to the visual arts, and algebraic projective geometry.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE521H1", :title=>"Inference Algorithms", :session=>"S", :area=>4, :description=>"Squared error and the Gaussian probability distribution. Maximum likelihood estimation. Logistic regression, neural networks, radial basis function networks. Occam's razor, validation, bagging, Bayesian techniques. Auto-encoders, principal components analysis, clustering. The EM algorithm. Matrix factorization. Markov models, hidden Markov models, the forward-backward algorithm, the Viterbi algorithm. Factor graphs, Bayesian networks, variable elimination, the sum-product algorithm, the max-product algorithm. Estimating graphical models. Applications to image classification, image processing, object tracking, speech recognition, telecommunications and genomics.", :prerequisites=>"STA286H1 S and ECE355H1 F or ECE302H1 F/S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"MIE331H1", :title=>"Physiological Control Systems", :session=>"S", :area=>47, :description=>"The purpose of this course is to provide undergraduate engineering students with an introduction to physiological concepts and selected physiological control systems present in the human body. Due to the scope and complexity of this field, this course will not cover all physiological control systems but rather a selected few such as the neuromuscular, cardiovascular, and endocrine control systems. This course will also provide an introduction to the structures and mechanisms responsible for the proper functioning of these systems. This course will combine linear control theory, physiology, and neuroscience with the objective of explaining how these complex systems operate in a healthy human body. The first part of the course will provide an introduction into physiology and give an overview of the main physiological systems. The second part of the course will focus on the endocrine system and its subsystems, including glucose regulation, thyroid metabolic hormones, and the menstrual cycle. The third part of the course will include discussion on the cardiovascular system and related aspects such as cardiac output, venous return, control of blood flow by the tissues, and nervous regulation of circulation. The fourth and final section of the course will focus on the central nervous system, the musculoskeletal system, proprioception, kinaesthetic, and control of voluntary motion. ", :prerequisites=>"CHE353H1F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>1.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Control, communications & signal processing $ Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE361H1", :title=>"Computer Networks I", :session=>"B", :area=>5, :description=>"Layered network architectures; overview of TCP/IP protocol suite. Introduction to sockets; introduction to application layer protocols. Peer-to-Peer Protocols: ARQ; TCP reliable stream service; flow control. Data Link Controls: Framing; PPP; HDLC. Medium access control and LANs: Aloha; Ethernet; Wireless LANs; Bridges. Packet Switching: Datagram and virtual circuit switching; Shortest path algorithms; Distance vector and link state algorithms.", :prerequisites=>"STA286H1 S or ECE302H1 F/S", :corequisites=>"ECE302H1 F/S. (Students must take the co-requisite, ECE302H1 F/S in the same term as ECE361H1 F/S, OR in a term before taking ECE361H1 F/S.)", :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Computer hardware & computer networks", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE461H1", :title=>"Internetworking", :session=>"F", :area=>56, :description=>"This course will cover the fundamentals of protocols for packet switching networks with emphasis on Internet type of networks including the following topics: the Internetworking concept and architectural model; data link layer (Ethernet and PPP); service interface; Internet addresses; address resolution protocol; Internet protocol (connectionless datagram delivery); routing IP datagrams; Internet control message protocol (error and control messages); subnet and supernet address extensions; ping program; traceroute program; user datagram protocol; reliable stream transport service (TCP); the socket interface; routing (GGP, EGP, IP, OSPF, HELLO); Internet multicasting; domain name system; applications such as HTTP, electronic mail, and SNMP; Internet security and firewall design; Ipv6, RSVP, flows, and ISIP.", :prerequisites=>"ECE361H1 F/S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Computer hardware & computer networks $ Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE552H1", :title=>"Computer Architecture", :session=>"F", :area=>5, :description=>"Performance analysis and metrics and cost. Instruction set architectures. Instruction-level parallelism: pipelining, superscalar, dynamic scheduling, VLIW processors.  Data-level prallelism:  vector processors, GPUs.  Thread-level parallelism: multiprocessors, multi-core, coherence, simultaneous multi-threading.  Memory hierarchies: caches and virtual memory support.  Simulation tools and methods.  Limited Enrollment.", :prerequisites=>"ECE243H1 S or ECE352H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Computer hardware & computer networks", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE342H1", :title=>"Computer Hardware", :session=>"S", :area=>5, :description=>"Arithmetic circuits, cubical representation of logic functions, digital system design, timing analysis, design of asynchronous circuits, testing of logic circuits.", :prerequisites=>"ECE241H1 F and ECE243H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Computer hardware & computer networks", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE466H1", :title=>"Computer Networks II", :session=>"S", :area=>5, :description=>"Traffic modeling; network calculus; traffic classification; traffic regulation: shaping, filtering, policing, leaky bucket; queueing systems; scheduling; quality of service: Diffserv and IntServ/RSVP; multi-protocol label switching; call admission control / congestion control; switching; pricing; optical networks.", :prerequisites=>"ECE361H1 F/S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Computer hardware & computer networks", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE344H1", :title=>"Operating Systems", :session=>"B", :area=>6, :description=>"Operating system structures, concurrency, synchronization, deadlock, CPU scheduling, memory management, file systems. The laboratory exercises will require implementation of part of an operating system.", :prerequisites=>"ECE244H1 F and ECE243H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>"ECE353H1 S", :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"ECE345H1", :title=>"Algorithms and Data Structures", :session=>"B", :area=>6, :description=>"Design and analysis of algorithms and data structures that are essential to engineers in every aspect of the computer hardware and software industry. Review of background material (recurrences, asymptotics, summations, trees and graphs). Sorting, search trees and balanced search trees, amortized analysis, hash functions, dynamic programming, greedy algorithms, basic graph algorithms, minimum spanning trees, shortest paths, introduction to NP completeness.", :prerequisites=>"ECE244H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Kernel", :year=>"upper"},
{:courseCode=>"CSC326H1", :title=>"Programming Languages", :session=>"F", :area=>6, :description=>"Study of programming styles and paradigms. Included are object-oriented scripting functional and logic-based approaches. Languages that support these programming styles will be introduced. Languages treated include Python, Lisp or Scheme and Prolog.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>"CSC324H1 F", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CSC343H1", :title=>"Introduction to Databases", :session=>"B", :area=>6, :description=>"Introduction to database management systems. The relational data model. Relational algebra. Querying and updating databases: the query language SQL. Application programming with SQL. Integrity constraints, normal forms, and database design. Elements of database system technology: query processing, transaction management.", :prerequisites=>"CSC165H1/CSC240H1/MAT137Y1/MAT157Y1; CSC207H1; CGPA 3.0/enrolment in a CSC subject POSt. Prerequisite for Engineering students only: ECE345/CSC190/CSC192", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>"CSC434H1.", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CSC418H1", :title=>"Computer Graphics", :session=>"B", :area=>6, :description=>"Identification and characterization of the objects manipulated in computer graphics, the operations possible on these objects, efficient algorithms to perform these operations, and interfaces to transform one type of object to another. Display devices, display data structures and procedures, graphical input, object modelling, transformations, illumination models, primary and secondary light effects; graphics packages and systems. Students, individually or in teams, implement graphical algorithms or entire graphics systems.", :prerequisites=>"CSC336H1/CSC350H1/CSC351H1/CSC363H1/CSC364H1/CSC365H1/CSC373H1/CSC375H1/CSC378HI/CSC463H1, MAT137Y1, CSC209H1/proficiency in C or C++ ; CGPA 3.0/enrolment in a CSC subject POSt. Prerequisite for Engineering students only: ECE345 or ECE352", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CSC444H1", :title=>"Software Engineering I", :session=>"F", :area=>6, :description=>"The software development process. Software requirements and specifications. Software design techniques. Techniques for developing large software systems; CASE tools and software development environments. Software testing, documentation and maintenance.", :prerequisites=>"ECE344H1 F/S or ECE353H1 S", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CSC467H1", :title=>"Compilers and Interpreters", :session=>"F", :area=>6, :description=>"Compiler organization, compiler writing tools, use of regular expressions, finite automata and context-free grammars, scanning and parsing, runtime organization, semantic analysis, implementing the runtime model, storage allocation, code generation.", :prerequisites=>"ECE352H1F", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE448H1", :title=>"Biocomputation", :session=>"F", :area=>67, :description=>"New technologies in molecular and cellular biology have allowed the collection of unprecedented amounts of biological data ranging from sequences to protein structures to gene expression. The need to synthesize knowledge from this abundant data is driving the convergence of the biological and computer sciences. This course will introduce the fundamental concepts and challenges in molecular biology and the computational and statistical approaches applied to model and address them. Course topics include basic concepts in molecular and structural biology, sequence-based algorithms (such as pairwise and multiple sequence alignment, statistical models), structure-based algorithms (such as energy models, homology modeling, threading), and systems biology algorithms (such as hierarchal and neural network clustering).", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software $ Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE454H1", :title=>"Computer Systems Programming", :session=>"F", :area=>6, :description=>"This course teaches fundamental techniques for programming computer systems, with an emphasis on obtaining good performance. The course will focus on system behaviour and operation, covering important concepts such as finite precision number representations, manipulation of bits and bytes at a low level, program operation at the machine level, memory allocation and management, the use of memory hierarchy for good performance, measuring and optimizing program performance. The course will also cover other selected advanced topics in programming techniques. Students will gain hands-on experience in a variety of topics and programming environments, and a deeper understanding of how to program computer systems for high performance and efficiency.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE419H1", :title=>"Distributed Systems", :session=>"S", :area=>6, :description=>"Design issues in distributed systems: heterogeneity, security, transparency, concurrency, fault-tolerance; networking principles; request-reply protocol; remote procedure calls; distributed objects; middleware architectures; CORBA; security and authentication protocols; distributed file systems; name services; global states in distributed systems; coordination and agreement; transactions and concurrency control; distributed transactions; replication.", :prerequisites=>"ECE344H1 F/S or ECE353H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>1.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE450H1", :title=>"Software Engineering II", :session=>"S", :area=>6, :description=>"A continuation of the material introduced in Software Engineering I, focusing on pragmatic structuring principles and design methodologies. Formal specification and validation of software systems. Object-oriented design and design patterns. Testing, metrics and maintenance of software systems. Reverse engineering. Safety-critical and real-time software systems. Emphasis is given to the design and development of large, complex software systems. A session project is normally required.", :prerequisites=>"CSC444H1 F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE540H1", :title=>"Optimizing Compilers", :session=>"S", :area=>6, :description=>"Theoretical and practical aspects of building modern optimizing compilers. Topics: intermediate representations, basic blocks and flow graphs, data flow analysis, partial evaluation and redundancy elimination, loop optimizations, register allocation, instruction scheduling, interprocedural memory hierarchy optimizations. Students will implement significant optimizations within the framework of a modern research compiler. Experience in C programming required.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"ECE568H1", :title=>"Computer Security", :session=>"S", :area=>6, :description=>"As computers permeate our society, the security of such computing systems is becoming of paramount importance. This course covers principles of computer systems security. To build secure systems, one must understand how attackers operate. This course starts by teaching students how to identify security vulnerabilities and how they can be exploited. Then techniques to create secure systems and defend against such attacks will be discussed. Industry standards for conducting security audits to establish levels of security will be introduced. The course will include an introduction to basic cryptographic techniques as well as hardware used to accelerate cryptographic operations in ATM's and webservers.", :prerequisites=>"ECE344H1 F/S or ECE353H1 S", :corequisites=>nil, :lectureHours=>3.0, :labHours=>3.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Software", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"APM384H1", :title=>"Partial Differential Equations", :session=>"F", :area=>7, :description=>"Boundary value problems and Sturm-Liouville theory for ordinary differential equations. Partial differential equations of first order, characteristics,Hamilton-Jacobi theory. Diffusion equations; Laplace transform methods. Harmonic functions, Green's functions for Laplace's equation, surface and volume distributions; Fourier transforms. Wave equation, characteristics; Green's functions for the wave equation; Huygens principle.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"BME455H1", :title=>"Cellular and Molecular Bioengineering II", :session=>"F", :area=>7, :description=>"Quantitative approach to understanding cellular behaviour. Using engineering tools (especially derived from transport phenomena and chemical kinetics) to integrate and enhance what is known about mammalian cell behaviour at the molecular level. The course combines mathematical modeling with biology and includes numerical methods, factorial design, statistics, empirical models, mechanistic models and mass transfer. Specific topics include: receptor-ligand interactions, cell adhesion and migration, signal transduction, cell growth and differentiation. Examples from gene therapy, and cellular and tissue engineering are used. ", :prerequisites=>"CHE353H1 and CHE354H1", :corequisites=>nil, :lectureHours=>3.0, :labHours=>1.5, :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CHE353H1", :title=>"Engineering Biology", :session=>"F", :area=>7, :description=>"Using a quantitative, problem solving approach, this course will introduce basic concepts in cell biology and physiology.  Various engineering modelling tools will be used to investigate aspects of cell growth and metabolism, transport across cell membranes, protein structure, homeostasis, nerve conduction and mechanical forces in biology. ", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>"BME105H1", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CIV220H1", :title=>"Urban Engineering Ecology", :session=>"F", :area=>7, :description=>"Core Course in the Environmental Engineering Minor Basic concepts of ecology within the context of urban environments. Response of organisms, populations, dynamic predator-prey and competition processes, and ecosystems to human activities. Thermodynamic basis for food chains, energy flow, biodiversity and ecosystem stability. Biogeochemical cycles, habitat fragmentation and bioaccumulation. Introduction to industrial ecology and life cycle assessment principles. Urban metabolism and material flow analysis of cities. Response of receiving waters to pollution and introduction to waste water treatment. Emphasis is on identifying the environment/engineering interface and minimizing environmental impacts.", :prerequisites=>"CHE112H1.", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>"EDV220H1", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CIV300H1", :title=>"Terrestrial Energy Systems", :session=>"B", :area=>7, :description=>"Core Course in the Sustainable Energy Minor Various earth systems for energy transformation, storage and transport are explored. Geological, hydrological, biological, cosmological and oceanographic energy systems are considered in the context of the Earth as a dynamic system, including the variation of solar energy received by the planet and the redistribution of this energy through various radiative, latent and sensible heat transfer mechanisms. It considers the energy redistribution role of large scale atmospheric systems, of warm and cold ocean currents, the role of the polar regions, and the functioning of various hydrological systems. The contribution and influence of tectonic systems on the surface systems is briefly introduced, as well the important role of energy storage processes in physical and biological systems, including the accumulation of fossil fuel reserves.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>"EDV300H1.", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"MAT389H1", :title=>"Complex Analysis", :session=>"F", :area=>7, :description=>"Course examines the following: analytic functions, Cauchy-Reimann equations, contour integration, Cauchy's theorem, Taylor and Laurent series, singularities, residue calculus, conformal mapping, harmonic functions, Dirichlet and Neumann problems and Poisson integral formulas. Course includes studies of linear differential equations in the complex plane, including Bessel and Legendre functions.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>"MAT290H1F", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"BME440H1", :title=>"Biomedical Engineering Technology and Investigation", :session=>"S", :area=>7, :description=>"An introduction to the principles of fundamental technologies used in biomedical engineering research including but not limited to tissue culture, protein assays or colourimetric enzymatic-based assays, spectroscopy, fluorescence microscopy, PCR, electrophoresis, DNAmanipulation and transfection. Since these technologies enable theinvestigation of a wide range of research questions with importantclinical implications, the main focus of the course is learning thesetechnologies while subsequent application within the lab will allowevidence-based investigation into specific research questions.Scientific literature (both good and bad) pertaining to each technologywill be reviewed as examples of conducting investigations.", :prerequisites=>"CHE353H1F, Engineering Biology", :corequisites=>nil, :lectureHours=>2.0, :labHours=>4.0, :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CHE230H1", :title=>"Environmental Chemistry", :session=>"S", :area=>7, :description=>"The chemical phenomena occurring in environmental systems are examined based on fundamental principles of organic, inorganic and physical chemistry. The course is divided into sections describing the chemistry of the atmosphere, natural waters and soils. The principles applied in the course include reaction kinetics and mechanisms, complex formation, pH and solubility equilibria and adsorption phenomena. Molecules of biochemical importance and instrumental methods of analysis relevant to environmental systems are also addressed. (formerly EDC230H1S)", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"CHE354H1", :title=>"Cellular and Molecular Biology", :session=>"S", :area=>7, :description=>"Using a quantitative, problem solving approach, this course will introduce basic concepts in cell biology and physiology.  Various engineering modelling tools will be used to investigate aspects of cell growth and metabolism, transport across cell membranes, protein structure, homeostasis, nerve conduction and mechanical forces in biology. ", :prerequisites=>"CHE353H1F", :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>2.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"EEB214H1", :title=>"Evolution and Adaptation", :session=>"S", :area=>7, :description=>"Evolution and adaptation through natural selection. Concepts and application based on faunal life goals of habitat survival, food acquisition, predator avoidance, and reproduction. Topics include: speciation, mutation, co-evolution, symbiosis, pollination, cannibalism, parasitism, eusociality, and sexual and parental conflict. Essays, debates, and reading required.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>"BIO120H1/BIO150Y1/ZOO214Y1/ZOO324Y1", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"MSE235H1", :title=>"Materials Physics", :session=>"S", :area=>7, :description=>"Application of solid state physics to describe properties of materials. Thermal properties of solids: lattice vibrations (phonons), heat capacity, thermal conductivity. Electrical properties of metals: simple circuits, resistivity of metals (classical and quantum descriptions), Seebeck, Peltier, and Thomson effects. Electrical properties of semiconductors: band structure and occupancy, conductivity, Hall effect, simple devices. Electrical properties of insulators: polarization, capacitance, optical properties, ferroelectric and piezoelectric materials. Magnetic properties: diamagnetism and paramagnetism, ferromagnetic and ferrimagnetic materials, magnetic domains, B-H curves.", :prerequisites=>nil, :corequisites=>nil, :lectureHours=>3.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"PHY395H1", :title=>"Physics of the Earth", :session=>"S", :area=>7, :description=>"Designed for students interested in the physics of the Earth and the planets. Study of the Earth as a unified dynamic system; determination of major internal divisions in the planet; development and evolution of the Earths large scale surface features through plate tectonics; the age and thermal history of the planet; Earths gravitational field and the concept of isostasy; mantle rheology and convection; Earth tides; geodetic measurement techniques, in particular modern space-based techniques. (formerly PHY359H1)", :prerequisites=>"PHY152H1/PHY254H1, MAT235Y1/MAT237Y1, MAT244H1 (Or permission of instructor)", :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>1.0, :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>"PHY359H1", :kernel=>"Technical Elective", :year=>"upper"},
{:courseCode=>"PSL432H1", :title=>"Theoretical Physiology", :session=>"S", :area=>7, :description=>nil, :prerequisites=>nil, :corequisites=>nil, :lectureHours=>2.0, :labHours=>"-", :tutorialHours=>"-", :discipline=>"ECE", :antiDescription=>nil, :areaName=>"Science/math electives", :exclusion=>nil, :kernel=>"Technical Elective", :year=>"upper"}]
=begin							 
							 {:title => 'Introduction to Electronic Devices', :courseCode => 'ECE335', :year_id => 3, :session =>'F', :area => 1},
							 {:title => 'Fundamental of Optics', :courseCode => 'ECE318', :year_id => 3, :session =>'S', :area => 1},
							 {:title => 'Semiconductor and Device Physics', :courseCode => 'ECE330', :year_id => 3, :session =>'S', :area => 1},
							 
							 {:title => 'Introduction to Micro- and Nano- Fabrication Technologies', :courseCode => 'ECE442', :year_id => 4, :session =>'F', :area => 1},
							 {:title => 'Passive Photonic Devices', :courseCode => 'ECE527', :year_id => 5, :session =>'F', :area => 1},
							 {:title => 'Advanced Electronic Devices', :courseCode => 'ECE553', :year_id => 5, :session =>'F', :area => 1},							 
							 {:title => 'Optical Communications and Networks', :courseCode => 'ECE469', :year_id => 4, :session =>'S', :area => 145},
							 {:title => 'Lasers and Detectors', :courseCode => 'ECE525', :year_id => 5, :session =>'S', :area => 1},							 
							 {:title => 'Introduction to Quantum Mechanics', :courseCode => 'PHY335', :year_id => 3, :session =>'S', :area => 17},
							 
							 {:title => 'Fundamentals of Electrical Energy Systems', :courseCode => 'ECE314', :year_id => 3, :session =>'F', :area => 2},
							 {:title => 'Fields and Waves', :courseCode => 'ECE320', :year_id => 3, :session =>'F', :area => 2},
							 
							 {:title => 'Introduction to Lighting Systems', :courseCode => 'ECE510', :year_id => 5, :session =>'F', :area => 2},
							 {:title => 'Microwave Circuits', :courseCode => 'ECE524', :year_id => 5, :session =>'F', :area => 2},
							 {:title => 'Advanced Power Electronics', :courseCode => 'ECE533', :year_id => 5, :session =>'F', :area => 2},
							 {:title => 'Medical Imaging', :courseCode => 'BME595', :year_id => 5, :session =>'S', :area => 2},
							 {:title => 'Energy Systems and Distributed Generation', :courseCode => 'ECE413', :year_id => 4, :session =>'S', :area => 2},
							 {:title => 'Radio and Microwave Wireless Systems', :courseCode => 'ECE422', :year_id => 4, :session =>'S', :area => 2},
							 {:title => 'Electric Drives', :courseCode => 'ECE463', :year_id => 4, :session =>'S', :area => 2},
							 
							 {:title => 'Analog Electronics', :courseCode => 'ECE331', :year_id => 3, :session =>'B', :area => 3},
							 {:title => 'Digital Electronics', :courseCode => 'ECE334', :year_id => 3, :session =>'B', :area => 3},
							 
							 {:title => 'Sensory Communication', :courseCode => 'ECE446', :year_id => 4, :session =>'F', :area => 3},
							 {:title => 'Analog Signal Processing Circuits', :courseCode => 'ECE512', :year_id => 5, :session =>'F', :area => 3},
							 {:title => 'Integrated Circuit Engineering', :courseCode => 'ECE534', :year_id => 5, :session =>'F', :area => 3},							 
							 {:title => 'VLSI Systems and Design', :courseCode => 'ECE451 ', :year_id => 4, :session =>'S', :area => 35},
							 {:title => 'Analog Integrated Circuits', :courseCode => 'ECE530', :year_id => 5, :session =>'S', :area => 3},
							 {:title => 'Digital Systems Design', :courseCode => 'ECE532', :year_id => 5, :session =>'S', :area => 35},
							 
							 {:title => 'Communication Systems', :courseCode => 'ECE316', :year_id => 3, :session =>'B', :area => 4},
							 {:title => 'Dynamic Systems and Control', :courseCode => 'ECE311 ', :year_id => 3, :session =>'S', :area => 4},
							 
							 {:title => 'Probability and Applications', :courseCode => 'ECE302', :year_id => 3, :session =>'B', :area => 47},
							 {:title => 'Control Systems', :courseCode => 'ECE410', :year_id => 4, :session =>'F', :area => 4},
							 {:title => 'Digital Signal Processing', :courseCode => 'ECE431', :year_id => 4, :session =>'B', :area => 4},
							 {:title => 'Neural Bioelectricity', :courseCode => 'ECE445', :year_id => 4, :session =>'F', :area => 4},
							 {:title => 'Sensory Communication', :courseCode => 'ECE446', :year_id => 4, :session =>'F', :area => 4},
							 {:title => 'Random Processes', :courseCode => 'ECE537', :year_id => 5, :session =>'F', :area => 4},
							 {:title => 'Real-Time Computer Control', :courseCode => 'ECE411', :year_id => 4, :session =>'S', :area => 4},
							 {:title => 'Digital Communication', :courseCode => 'ECE417', :year_id => 4, :session =>'S', :area => 4},
							 {:title => 'Multimedia Systems', :courseCode => 'ECE462', :year_id => 4, :session =>'S', :area => 4},
							 {:title => 'Wireless Communication', :courseCode => 'ECE464', :year_id => 4, :session =>'S', :area => 4},
							 {:title => 'Robot Modeling and Control', :courseCode => 'ECE470', :year_id => 4, :session =>'S', :area => 4},
							 {:title => 'Intelligent Image Processing', :courseCode => 'ECE516', :year_id => 5, :session =>'S', :area => 4},
							 {:title => 'Inference Algorithms', :courseCode => 'ECE521', :year_id => 5, :session =>'S', :area => 4},
							 {:title => 'Physiological Control Systems', :courseCode => 'MIE331', :year_id => 3, :session =>'S', :area => 47},
							 
							 {:title => 'Computer Networks I', :courseCode => 'ECE361', :year_id => 3, :session =>'B', :area => 5},
							 {:title => 'Computer Hardware', :courseCode => 'ECE342', :year_id => 3, :session =>'S', :area => 5},
							 
							 {:title => 'Internetworking', :courseCode => 'ECE461', :year_id => 4, :session =>'F', :area => 56},
							 {:title => 'Computer Architecture', :courseCode => 'ECE552', :year_id => 5, :session =>'F', :area => 5},
							 {:title => 'Computer Networks II', :courseCode => 'ECE466', :year_id => 4, :session =>'S', :area => 5},
							 
							 {:title => 'Operating Systems', :courseCode => 'ECE344', :year_id => 3, :session =>'B', :area => 6},
							 {:title => 'Algorithms and Data Structures', :courseCode => 'ECE345', :year_id => 3, :session =>'B', :area => 6},
							  
							 {:title => 'Programming Languages', :courseCode => 'CSC326', :year_id => 3, :session =>'F', :area => 6},
							 {:title => 'Introduction to Databases', :courseCode => 'CSC343', :year_id => 3, :session =>'B', :area => 6},
							 {:title => 'Computer Graphics', :courseCode => 'CSC418', :year_id => 4, :session =>'B', :area => 6},
							 {:title => 'Software Engineering I', :courseCode => 'CSC444', :year_id => 4, :session =>'F', :area => 6},
							 {:title => 'Compilers and Interpreters', :courseCode => 'CSC467', :year_id => 4, :session =>'F', :area => 6},
							 {:title => 'Biocomputation', :courseCode => 'ECE448', :year_id => 4, :session =>'F', :area => 67},
							 {:title => 'Computer Systems Programming', :courseCode => 'ECE454', :year_id => 4, :session =>'F', :area => 6},
							 {:title => 'Distributed Systems', :courseCode => 'ECE419', :year_id => 4, :session =>'S', :area => 6},
							 {:title => 'Software Engineering II', :courseCode => 'ECE450', :year_id => 4, :session =>'S', :area => 6},
							 {:title => 'Optimizing Compilers', :courseCode => 'ECE540', :year_id => 5, :session =>'S', :area => 6},
							 {:title => 'Computer Security', :courseCode => 'ECE568', :year_id => 5, :session =>'S', :area => 6},
							 
							 {:title => 'Partial Differential Equations', :courseCode => ' APM384', :year_id => 3, :session =>'F', :area => 7},
							 {:title => 'Cellular and Molecular Bioengineering II', :courseCode => 'BME455', :year_id => 4, :session =>'F', :area => 7},
							 {:title => 'Engineering Biology', :courseCode => 'CHE353', :year_id => 3, :session =>'F', :area => 7},
							 {:title => 'Urban Engineering Ecology', :courseCode => 'CIV220', :year_id => 3, :session =>'F', :area => 7},
							 {:title => 'Terrestrial Energy Systems', :courseCode => 'CIV300', :year_id => 3, :session =>'B', :area => 7},
							 {:title => 'Complex Analysis', :courseCode => 'MAT389', :year_id => 3, :session =>'F', :area => 7},
							 
							 {:title => 'Biomedical Engineering Technology and Investigation', :courseCode => 'BME440', :year_id => 3, :session =>'S', :area => 7},
							 {:title => 'Environmental Chemistry', :courseCode => 'CHE230', :year_id => 3, :session =>'S', :area => 7},
							 {:title => 'Cellular and Molecular Biology', :courseCode => 'CHE354', :year_id => 3, :session =>'S', :area => 7},
							 {:title => 'Evolution and Adaptation', :courseCode => 'EEB214', :year_id => 3, :session =>'S', :area => 7},
							 {:title => 'Materials Physics', :courseCode => 'MSE235', :year_id => 3, :session =>'S', :area => 7},
							 {:title => 'Physics of the Earth', :courseCode => 'PHY395', :year_id => 3, :session =>'S', :area => 7},
							 {:title => 'Theoretical Physiology', :courseCode => 'PSL432', :year_id => 4, :session =>'S', :area => 7}
=end
							 


DThread.create [
								{:title => 'Anti-Aliasing', 
								 :question => 'How does an anti-aliasing filter affect the quality of the sample?', 
								 :created_at => Time.now, 
								 :updated_at => Time.now, 
								 :courseCode =>  'ECE216', 
								 :course_id => nil},
								
								{:title => 'Symmetry between electricity and magnetism', 
								:question => "If currents produce magnetic fields, then why is it that magnetic fields don't produce currents, i.e. why does it have to be a moving magnetic field.", 
								:created_at => Time.now, 
								:updated_at => Time.now, 
								:courseCode =>  'ECE221', 
								:course_id => nil},
								
								{:title => 'Operating Systems', 
								 :question => 'What is the difference between Unix and Linux', 
								 :created_at => Time.now, 
								 :updated_at => Time.now, 
								 :courseCode =>  'ECE344', 
								 :course_id => nil},
								 
								 {:title => 'File Descriptor',
								 	:question => "What is a file descriptor, and why do we need to pass it as a parameter in read/write calls?",
								 	:created_at => Time.now,
								 	:updated_at => Time.now,
								 	:courseCode => 'ECE344',
								 	:course_id => nil},
								 	
								 	{:title => 'Internal fragmentation',
								 	:question => 'When does it occur?',
								 	:created_at => Time.now,
								 	:updated_at => Time.now,
								 	:courseCode => 'ECE344',
								 	:course_id => nil},
								 	
								 {:title => "Dining Philosopher's problem",
								 	:question => 'What is it?',
								 	:created_at => Time.now,
								 	:updated_at => Time.now,
								 	:courseCode => 'ECE344',
								 	:course_id => nil},
								 	
								 {:title => "Characterisitic Impedance",
								 	:question => 'How do you determine it?',
								 	:created_at => Time.now,
								 	:updated_at => Time.now,
								 	:courseCode => 'ECE320',
								 	:course_id => nil}
							]


# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
